apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-dashboard
  template:
    metadata:
      labels:
        app: sales-dashboard
    spec:
      containers:
      - name: flask-app
        image: your-dockerhub-username/sales-dashboard:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sales-dashboard-service
spec:
  type: LoadBalancer
  selector:
    app: sales-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
